apiVersion: v2
name: agent-memory-server
description: Redis Agent Memory Server
type: application
version: 0.2.0
appVersion: "0.14.0"
keywords:
  - agent
  - memory
  - redis
home: https://redis.github.io/agent-memory-server/
sources:
  - https://github.com/redis/agent-memory-server
maintainers:
  - name: Redis Labs
    url: https://redis.io
