#

disableAuth: "true"
replicaCount: 1
longTermMemory: "true"
topicExtraction: "true"
enableNer: "true"
registry: "docker.io"
repository: "redislabs"
image: "agent-memory-server"
tag: "latest"
port: 8000

model:
  generation: "gpt-5.2-chat-latest"
  fast: "gpt-5-mini"
  embedding: "text-embedding-3-small"

redis:
  secretName: redis-url-secret
  url: "redis://localhost:6379"
  prefix: "redis+cluster"
  service: "redb"
  namespace: ""
  port: 12000

openai:
  secretName: openai-api-key-secret
  key: ""

externalSecret:
  enabled: true
  store:
    kind: ClusterSecretStore
    name: "secret-store"
  keys:
    openai: "openai-api-key"
    password: "redis-db-password-key"
