FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-install-project --no-dev

COPY src/ ./src/

RUN uv sync --frozen --no-dev

EXPOSE 8088

ENTRYPOINT ["uv", "run", "memory_demo_grpc"]
