apiVersion: v2
name: agent-memory-demo
description: Redis Agent Memory Server Demo
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - agent
  - memory
  - redis
home: https://github.com/mminichino/redis-agent-memory-demo
sources:
  - https://github.com/mminichino/redis-agent-memory-demo
maintainers:
  - name: Michael Minichino
    url: https://github.com/mminichino/redis-agent-memory-demo
