#

name: agent-memory-demo
service: agent-memory-demo
replicaCount: 1
password: ""

server:
  prefix: "redis+cluster"
  url: ""
  service: "redb"
  namespace: "redis"
  port: 12000

keys:
  openai: ""
  tavily: ""

secrets:
  openai: "openai-api-key-demo-secret"
  tavily: "tavily-api-key-demo-secret"
  password: "agent-memory-demo-password"
  url: "agent-memory-demo-redis-url"

dns:
  domain: ""

ingress:
  enabled: true
  type: "haproxy"
  username: "redis"
  password: "password"

tls:
  enabled: true
  secretName: agent-memory-demo-tls

externalSecret:
  enabled: true
  store:
    kind: ClusterSecretStore
    name: "secret-store"
  keys:
    openai: "openai-api-key"
    tavily: "tavily-api-key"
    password: "demo-ui-password"
    url: "redis-password"
