apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.url }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $service := .Values.server.service }}
  {{- $namespace := .Values.server.namespace | default .Release.Namespace }}
  {{- $port := .Values.server.port }}
  {{- $url := printf "http://%s.%s.svc.cluster.local:%v" $service $namespace $port }}
  AGENT_MEMORY_SERVER_URL: {{ $url | b64enc }}
