{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.openai }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.keys.openai | b64enc }}
{{- end }}
