{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.password }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  APP_PASSWORD: {{ .Values.password | b64enc }}
{{- end }}
