{{- if and .Values.ingress.enabled .Values.dns.domain }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.password }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if eq .Values.ingress.type "haproxy" }}
  {{ .Values.ingress.username }}: {{ htpasswd .Values.ingress.username .Values.ingress.password | splitList ":" | last | b64enc }}
  {{- else }}
  auth: {{ htpasswd .Values.ingress.username .Values.ingress.password | trim | b64enc }}
  {{- end }}
{{- end }}
