{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.url }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redis.url: {{ .Values.server.url | b64enc }}
{{- end }}
