apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service }}-redis"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 10100
      targetPort: 6379
      protocol: TCP
  selector:
    app: agent-memory-demo
