{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.url }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: {{ .Values.secrets.url }}
    creationPolicy: Owner
    template:
      data:
        redis.url: "{{ .Values.server.prefix }}://default:{{ `{{` }} .password {{ `}}` }}@{{ .Values.server.service }}.{{ .Values.server.namespace }}.svc.cluster.local:{{ .Values.server.port }}/0"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.keys.redis }}
{{- end }}
