apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7860
      targetPort: 7860
      protocol: TCP
  selector:
    app: agent-memory-demo
