{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.tavily }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TAVILY_API_KEY: {{ .Values.keys.tavily | b64enc }}
{{- end }}
