{{- if and .Values.tls.enabled .Values.dns.domain -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: agent-memory-demo
type: kubernetes.io/tls
data:
  {{- $domain := .Values.dns.domain }}
  {{- $prefix := .Values.name }}
  {{- $name := printf "%s.%s" $prefix $domain }}
  {{- $host := list $name }}
  {{- $cert := genSelfSignedCert $prefix nil $host 365 }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end -}}
