{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_URL: {{ .Values.redis.url | b64enc }}
{{- end }}
