{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.secretName }}
  namespace: {{ default .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: {{ .Values.redis.secretName }}
    creationPolicy: Owner
    template:
      data:
        REDIS_URL: "{{ .Values.redis.prefix }}://default:{{ `{{` }} .password {{ `}}` }}@{{ .Values.redis.service }}.{{ .Values.redis.namespace | default .Release.Namespace }}.svc.cluster.local:{{ .Values.redis.port }}/0"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.keys.password }}
{{- end }}
